_id: 6810b4382e6854005053aa59
title: Audit Log
description: Describe your new bucket
icon: view_stream
primary: action
readOnly: false
history: false
properties:
  organization:
    type: relation
    title: organization
    description: Description of the organization input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6810b3292e6854005053aa36
    dependent: false
    primary: name
  team:
    type: relation
    title: team
    description: Description of the team input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6810b3e32e6854005053aa45
    dependent: false
    primary: name
  resource:
    type: relation
    title: resource
    description: Description of the resource input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6810b3f12e6854005053aa4a
    dependent: false
    primary: name
  user:
    type: relation
    title: user
    description: Description of the user input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 63ac7c8e9b0b86002b374178
    dependent: false
    primary: name
  action:
    type: string
    title: action
    description: Description of the action input
    options:
      position: bottom
  status:
    type: string
    title: status
    description: Description of the status input
    options:
      position: bottom
    enum:
      - granted
      - forbidden
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
    default: :created_at
acl:
  write: true==true
  read: true==true
order: 18
category: RBAC
