_id: 6810e7572e6854005053ae91
title: Role Assignment
description: Describe your new bucket
icon: view_stream
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
  role_actions:
    type: relation
    title: role_actions
    description: Description of the role_actions input
    options:
      position: bottom
    relationType: onetomany
    bucketId: 6810b41c2e6854005053aa54
    dependent: false
    primary: title
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
    default: :created_at
acl:
  write: true==true
  read: true==true
order: 17
category: RBAC
