_id: 6810b41c2e6854005053aa54
title: Role Action
description: Describe your new bucket
icon: view_stream
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
  role:
    type: relation
    title: role
    description: Description of the role input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6810b8812e6854005053aace
    dependent: false
    primary: name
  organization:
    type: relation
    title: organization
    description: Description of the organization input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6810b3292e6854005053aa36
    dependent: false
    primary: name
  team:
    type: relation
    title: team
    description: Description of the team input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6810b3e32e6854005053aa45
    dependent: false
    primary: name
  resource:
    type: relation
    title: resource
    description: Description of the resource input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 6810b3f12e6854005053aa4a
    dependent: false
    primary: name
  actions:
    type: array
    title: actions
    description: Description of the actions input
    options:
      position: bottom
    items:
      title: Title of the items
      type: string
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
    default: :created_at
acl:
  write: true==true
  read: true==true
order: 16
category: RBAC
