_id: 68123c2b2e6854005053c596
name: Invitation
language: javascript
timeout: 30
triggers:
  accept:
    type: http
    active: true
    options:
      method: Post
      path: /invitation/accept
      preflight: true
env:
  API_SECRET_KEY: "{API_SECRET_KEY}"
memoryLimit: 100
category: RBAC
order: 6
